ALTER TABLE "Document" ADD COLUMN "totalChunks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Document" ADD COLUMN "processedChunks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Document" ADD COLUMN "embeddedChunks" INTEGER NOT NULL DEFAULT 0;
